src/Entrax/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.core.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}
    ),
    url(r'^signup/$', 'apps.core.views.sign_up'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^prueba/$', 'apps.rider.views.prueba'),
    url(r'^prueba/(?P<country>\d+)/$', 'apps.rider.views.prueba'),
    url(
        r'^prueba/(?P<country>\d+)/(?P<state>\d+)/$', 
        'apps.rider.views.prueba'),
    url(
        r'^prueba/(?P<country>\d+)/(?P<state>\d+)/(?P<citie>\d+)', 
        'apps.rider.views.prueba'),

    url(
        r'^hola_mundo/$',
        'apps.championship.views.hola_mundo'
    ),
    url(
        r'^saludo/(?P<nombre>[a-zA-Z@.-_]+)/',
        'apps.championship.views.hola_mundo'
    ),
    
    url(
        r'^championship_list/$',
        'apps.championship.views.championship_list'
    ),
    url(
        r'^championship_list/(?P<discipline_parametro>\d+)/',
        'apps.championship.views.championship_list'
    )
)

src/apps/core/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" % (self.name,)


class State(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, blank=True, null=True)

    def __unicode__(self):
        return "%s" % (self.name)


class Citie(models.Model):
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State, blank=True, null=True)

    def __unicode__(self):
        return "%s" % (self.name,)

    @property
    def country(self):
        try:
            return self.state.country
        except:
            return None

    def get_location(self):
        return "%s, %s, %s" % (self.name, self.state, self.country)

src/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html lang="es" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Entrax</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

    <!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
    <!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
    <!--script src="js/less-1.3.3.min.js"></script-->
    <!--append ‘#!watch’ to the browser URL, then refresh the page. -->
    
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
  
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  
  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/img/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/img/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/img/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="/static/img/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="/static/img/favicon.ico">
  
  <!-- CUSTOM CSS -->
  <!-- Google font api -->
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
  <!-- Awesome fonts -->
  <link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.min.css">    
  
  <!-- Bootstrap script -->
  <script type="text/javascript" src="/static/js/jquery.js"></script>
  <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>

</head>

<body id="top" class="">
<!-- NAV BAR
============================================= -->  
<nav class="navbar-default navbar-inverse navbar-fixed-top navbarEffect" role="navigation">
  <div class="container">
  
<div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> </button> 
<h2 style="margin:0px;"><a class="navbar-brand" href="#top">ENTRAX</a> </h2>
</div><!-- /.navbar-header -->


<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li class="active">
    <a href="index.html">Inicio</a>
    </li>
      
      <!-- dropdown -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">ENTRAX <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="registrate.html">Que / Quienes</a></li>
            <li><a href="registrate.html">Valores</a></li>
            <li><a href="registrate.html">Unite!</a></li>
            <li class="divider"></li>
            <li><a href="#">Privacidad</a></li>
            <li><a href="#">Términos de uso</a></li>
          </ul>
        </li><!-- /.dropdown -->
      

      <!-- dropdown -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">OPCIONES <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="registrate.html">Federaciones</a></li>
            <li><a href="registrate.html">Campeonatos</a></li>
            <li><a href="registrate.html">Carreras</a></li>
            <li><a href="registrate.html">Clubes</a></li>
            <li><a href="registrate.html">Pilotos</a></li>
            <li><a href="registrate.html">Marcas</a></li>
          </ul>
        </li><!-- /.dropdown -->
      
      <!-- dropdown -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">EL EGO <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="registrate.html">PACK Fotos Pro</a></li>
            <li><a href="registrate.html">Tus Fotos</a></li>
            <li><a href="registrate.html">Foto del Mes!</a></li>
            <li><a href="registrate.html">Foto ENTRAX</a></li>
          </ul>
        </li><!-- /.dropdown -->
      
      <!-- dropdown -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">AYUDAS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="registrate.html">Como es la cosa?</a></li>
            <li><a href="registrate.html">Mi Perfil</a></li>
            <li><a href="registrate.html">Como arranco?</a></li>
            <li><a href="registrate.html">Otras yerbas</a></li>
          </ul>
        </li><!-- /.dropdown -->
    <li class="">
    <a href="contacto.html">Contacto</a>
    </li>
  </ul>
</div>   
     
   </div> <!-- /.container -->                  
</nav>  <!-- /.nav -->
<!-- /NAV BAR
============================================= -->  

<!-- BG IMAGE (fixed)
============================================= -->   
    
<div id="wallpaper">
    <div class="imageCenterer">
        <a target="_blank" href="http://www.acerbis.com/"><img class="img-responsive" alt="bg" src="/static/img/moto-bg.jpg"></a>
    </div>
</div>
    
<!-- /.BG IMAGE (fixed)
============================================= -->    
<div id="main" class="container">
<div id="top-spacer"></div>
    
    
<!-- /BANNER ADS  -->   
    <div class="row">
        
        <div class="col-md-4">
            <img style="float:left;" class="img-responsive" alt="" src="/static/img/logo-entrax.png">
        </div><!-- /col-md-4  --> 
        
        <div class="col-md-8">
            <img style="float:left;" class="img-responsive" alt="" src="/static/img/banner-logo.jpg"> 
        </div><!-- /col-md-8  --> 
        
    </div><!-- /row  -->          
<!-- /BANNER ADS  -->       

{% block content%}{% endblock %}
</div>


<!-- /FOOTER
============================================= -->  
    

    
<!-- FOOTER FIXED
============================================= -->
<section class="footer-fixed">
    <div class="container">
    <div class="row">
        
        <div class="col-md-6 column">
        &copy;2014 Frank Labs
        </div> <!-- /.col-md-6 -->
        
        <div class="col-md-6 column">
        <span style="float:right;">by <a href="http://www.maloncreativo.com" target="_blank">Malón Creativo</a></span>
        </div><!-- /.col-md-6 -->
        
    </div><!-- /.row -->
    </div><!-- /.container -->        
</section>
<!-- /FOOTER FIXED
============================================= --> 


    
    

<!-- GOTO TOP
============================================= -->
<a href="#top" class="goto-top"><i class="fa fa-arrow-circle-o-right fa-3x fa-rotate-270"></i></a>
<!-- /GOTO TOP
============================================= -->



    
    

<!-- EXTRA SCRIPTS
============================================= -->

    
<!-- onePageNav script -->
<script type="text/javascript" src="/static/js/jquery.scrollTo.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.localScroll.js"></script>


<!-- customs script -->
<script type="text/javascript" src="/static/js/scripts.js"></script>



<!-- .GOTO TOP script -->
     <script>            
            jQuery(document).ready(function() {
                var offset = 550;
                var duration = 500;
                jQuery(window).scroll(function() {
                    if (jQuery(this).scrollTop() > offset) {
                        jQuery('.goto-top').fadeIn(duration);
                    } else {
                        jQuery('.goto-top').fadeOut(duration);
                    }
                });
                
                jQuery('.goto-top').click(function(event) {
                    event.preventDefault();
                    jQuery('html, body').animate({scrollTop: 0}, duration);
                    return false;
                })
            });
        </script>
<!-- /.GOTO TOP script -->
     
<!-- /SCRIPTS
============================================= -->

</body>
</html>

src/templates/champ_inscription.html
<form action="/championship/inscription/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

src/templates/new_rider.html
<form action="/rider/new_rider/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

src/templates/prueba.html
{% extends 'base.html'%}

{% block content %}
<style type="text/css">
    .input_text{
        background-color: yellow
    }
</style>
<div id="content-outer">
    <div class="row">
        <div class="col-md-8">
            <form name='formulario' method='POST' action='.'>
                {% csrf_token %}
                {{ form.as_p }}

                <label for='id_country'>
                    Country: 
                        <select id="country" class="form-control" 
                                onChange="javascript: agregarEstados(this.form)">
                            <option value="">---------</option>
                            {% for item in country_lst%}
                                <option value="{{ item.id }}">{{item}}</option>
                            {% endfor %}
                        </select>
                </label>
                <label for='id_state'>
                    State: 
                        <select id="state" class="form-control"
                                    onChange="javascript: agregarCiudades(this.form)">
                            <option value="">---------</option>
                            {% for item in state_lst %}
                                <option value="{{ item.id }}">{{item}}</option>
                            {% endfor %}
                        </select>
                </label>
                <label for='id_citie'>
                    Citie: 
                        <select id="citie" class="form-control">
                            <option value="">---------</option>
                            {% for item in citie_lst %}
                                <option value="{{ item.id }}">{{item}}</option>
                            {% endfor %}
                        </select>
                </label>
                <br><br>

                <button type="submit">aceptar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}